@startuml SafeIsland_CredentialPresentation

autonumber
skinparam sequence {
ArrowThickness 3
}

skinparam roundcorner 10
skinparam maxmessagesize 300

box "Citizen" #f1f9ff
  actor "Citizen\nwith\nmobile" as CI
end box

box "Secure\nMessaging\nServer" #f1f9ff
  database "Messaging\nServer" as SM
end box

box "Verifier" #f1f9ff
  actor "Operator\nwith\nmobile" as VE
end box

box "Trust Framework" #f1f9ff
  participant "Universal\nResolver" as UR
end box

== Generate the Verifiable Presentation ==
VE -> VE: QR with Verifier DID
note left: QR is printed visibly\nin Verifier premises
CI -> CI: Open QR scanner
VE -[#0000FF]-> CI: Scan the QR with DID of Verifier

CI -> UR: Resolve and verify Identity of Verifier
activate UR
return Get DID Document with info about Verifier
CI -> CI: Display info about Verifier

CI -> CI: Accept and generate Verifiable Presentation

== Send Presentation to Verifier ==
CI -> SM: Store Presentation temporarily
activate SM
return OK
CI -> CI: Generate & Display QR

VE -> VE: Open QR scanner
CI -[#0000FF]-> VE: Scan QR with URL

VE -> SM: Get Presentation data
activate SM
SM -> SM: Presentation deleted automatically
return OK

== Verification of Credential ==
VE -> VE: Verify Credential
VE -> UR: Verify signature of Credential
VE -> VE: Display Credential to Verifier

@enduml

