@startuml SafeIsland_Components
package "Issuer Entity" {

  card OperatorApp [
    <b>Operator App
    ====
    Data entry for Citizen
    and Certificates
  ]


  node IssuerServer [
    <b>Issuer server
    ====
    Manages Certificates
  ]

  database IssuerDatabase [
    <b>Issuer database
    ====
    Encrypted certificates
  ]

}

  card CitizenApp [
    <b>Citizen WebApp
    ====
    Downloaded from Issuer server
    or any other secure server
  ]

  node SecureMessageServer [
    <b>Secure Message server
    ====
    Secure sending and
    receiving of Credentials
    ---
    Can be hosted by many
    trusted participants
  ]



package "Verifier Entity" {

  card VerifierApp [
    <b>Verifier App
    ====
    Verifies
    certificates
  ]


  node VerifierServer [
    <b>Verifier server
    ====
    Logs verifications
    for auditing
  ]

  database VerifierDatabase [
    <b>Verifier database
    ====
    Logs verifications
    Privacy-preserving
  ]


}

package Blockchain {

  database Identities [
    <b>Legal Person Identities
    ====
    Identities of Legal Persons:
    - Issuers and Verifiers
    ----
    Never personal information
  ]

  node VerifierNode [
    <b>Verifier node
  ]

  node IssuerNode [
    <b>Issuer node
  ]

}

OperatorApp .r.> CitizenApp: QR
OperatorApp --> IssuerServer
IssuerServer -- IssuerDatabase
OperatorApp --> SecureMessageServer
CitizenApp --> SecureMessageServer
CitizenApp .r.> VerifierApp: QR
VerifierApp --> SecureMessageServer

VerifierApp --> VerifierServer
VerifierServer -- VerifierDatabase

IssuerServer --> IssuerNode
VerifierNode -u-> VerifierServer

IssuerNode -- Identities
VerifierNode -- Identities

@enduml

