@startuml SafeIsland_CredentialIssuance

autonumber
skinparam sequenceArrowThickness 3
skinparam roundcorner 10
skinparam maxmessagesize 300

box "Issuer" #f1f9ff
  actor "Operator\nwith\nmobile" as OP
  database "Issuer\nbackend" as IS
end box

box "Citizen" #f1f9ff
  actor "Citizen\nwith\nmobile" as CI
end box

box "Trust Framework" #f1f9ff
  participant "Universal\nResolver" as UR
end box

== Obtain Informed Consent from Citizen ==
CI -[#0000FF]-> OP: Provide Informed Consent
note right: Citizen is informed\nthat will provide\npersonal data 
OP -[#0000FF]-> CI: Physical identification of Citizen

== Credential generation ==
OP -> IS: Enter Citizen data
OP -> IS: Enter Credential data
OP -> IS: Generate & Save Credential
OP -> OP: Display Credential QR

== Citizen receives Credential ==
CI -> CI: Opens QR scanner
OP -[#0000FF]-> CI: Scan Credential QR
note right: QR contains URL\nto obtain Credential data
CI -> IS: Request full Credential
activate IS
return Receive Credential data

== Verification of Credential ==
CI -> CI: Verify Credential
CI -> UR: Verify signature of Credential
CI -> CI: Save Credential


@enduml

