@startjson SafeIsland_DataModelSamples1

{
      "Header": {
            "AnalysisID": "string: unique ID of analysis",
            "Version": "number: version number of analysis",
            "Date": "date: date when test sample taken",
            "Patient": "string: surname and name",
            "ID type": "string: type of identifier",
            "ID number": "string: identifier number",
            "Entity": "string: name of entity performing test",
            "Address": "string: postal address of entity"
      },
      "Analysis details": {
            "Sample": ""
      }
}
@endjson
